//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5477
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPClient4Windows {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFPClient4Windows.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Connection failed:
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DSIGetStatus issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueDSIGetStatus {
            get {
                return ResourceManager.GetString("IssueDSIGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DSIOpenSession issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueDSIOpenSession {
            get {
                return ResourceManager.GetString("IssueDSIOpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPCloseFork issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPCloseFork {
            get {
                return ResourceManager.GetString("IssueFPCloseFork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPCreateDir issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPCreateDir {
            get {
                return ResourceManager.GetString("IssueFPCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPCreateFile issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPCreateFile {
            get {
                return ResourceManager.GetString("IssueFPCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPDelete issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPDelete {
            get {
                return ResourceManager.GetString("IssueFPDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPEnumerate issued {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPEnumerate {
            get {
                return ResourceManager.GetString("IssueFPEnumerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPEnumerateExt issued {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPEnumerateExt {
            get {
                return ResourceManager.GetString("IssueFPEnumerateExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPEnumerateExt2 issued {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPEnumerateExt2 {
            get {
                return ResourceManager.GetString("IssueFPEnumerateExt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPGetSrvrParms issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPGetSrvrParms {
            get {
                return ResourceManager.GetString("IssueFPGetSrvrParms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin {
            get {
                return ResourceManager.GetString("IssueFPLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_2w issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_2w {
            get {
                return ResourceManager.GetString("IssueFPLogin_2w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_2w_2 issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_2w_2 {
            get {
                return ResourceManager.GetString("IssueFPLogin_2w_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_Cleartext_Password issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_Cleartext_Password {
            get {
                return ResourceManager.GetString("IssueFPLogin_Cleartext_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_DHX issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_DHX {
            get {
                return ResourceManager.GetString("IssueFPLogin_DHX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_DHX_2 issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_DHX_2 {
            get {
                return ResourceManager.GetString("IssueFPLogin_DHX_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_DHXv2_1 issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_DHXv2_1 {
            get {
                return ResourceManager.GetString("IssueFPLogin_DHXv2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_DHXv2_2 issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_DHXv2_2 {
            get {
                return ResourceManager.GetString("IssueFPLogin_DHXv2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogin_DHXv2_3 issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogin_DHXv2_3 {
            get {
                return ResourceManager.GetString("IssueFPLogin_DHXv2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPLogout issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPLogout {
            get {
                return ResourceManager.GetString("IssueFPLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPMoveAndRename issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPMoveAndRename {
            get {
                return ResourceManager.GetString("IssueFPMoveAndRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPOpenFork issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPOpenFork {
            get {
                return ResourceManager.GetString("IssueFPOpenFork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPRename issued
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IssueFPRename {
            get {
                return ResourceManager.GetString("IssueFPRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the following incomplete file?
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryDeleteIncompleteFile {
            get {
                return ResourceManager.GetString("QueryDeleteIncompleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to quit? File transfer in progress will be disturbed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryFormClosing {
            get {
                return ResourceManager.GetString("QueryFormClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File deletion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReasonFileDelete {
            get {
                return ResourceManager.GetString("ReasonFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filename numbering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReasonFileNumbering {
            get {
                return ResourceManager.GetString("ReasonFileNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReasonFileRename {
            get {
                return ResourceManager.GetString("ReasonFileRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder creation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReasonFolderCreate {
            get {
                return ResourceManager.GetString("ReasonFolderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder deletion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReasonFolderDelete {
            get {
                return ResourceManager.GetString("ReasonFolderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move or rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReasonMoveOrRename {
            get {
                return ResourceManager.GetString("ReasonMoveOrRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using AFP ver: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportAFPVer {
            get {
                return ResourceManager.GetString("ReportAFPVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth failed.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportAuthFailed {
            get {
                return ResourceManager.GetString("ReportAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportAuthFailed1L {
            get {
                return ResourceManager.GetString("ReportAuthFailed1L", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Auth Ok
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportAuthOk {
            get {
                return ResourceManager.GetString("ReportAuthOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} failed: {1}, {2}, {3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportErr {
            get {
                return ResourceManager.GetString("ReportErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} failed: {1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportEx {
            get {
                return ResourceManager.GetString("ReportEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   evExit is shot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportExitShotException {
            get {
                return ResourceManager.GetString("ReportExitShotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetSrvrInfo result:
        ///  MachineType: {0} 
        ///  AFP versions: {1} 
        ///  UAMs: {2} 
        ///  Server name: {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportGetSrvrInfo {
            get {
                return ResourceManager.GetString("ReportGetSrvrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session count limit hit.。
        ///- Restart your Mac, or restart AFP sharing service,
        ///- Reconnect after a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportkFPNoMoreSessions {
            get {
                return ResourceManager.GetString("ReportkFPNoMoreSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to refresh:
        ///
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportRefreshSelFailed {
            get {
                return ResourceManager.GetString("ReportRefreshSelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result: {0}, {1}, {2}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportResultNg {
            get {
                return ResourceManager.GetString("ReportResultNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result: Ok
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportResultOk {
            get {
                return ResourceManager.GetString("ReportResultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transmit failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportTransmitFailureException {
            get {
                return ResourceManager.GetString("ReportTransmitFailureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth method: {0} 
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportUAM {
            get {
                return ResourceManager.GetString("ReportUAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User cancel requested. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportUserCancelException {
            get {
                return ResourceManager.GetString("ReportUserCancelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed:
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportUtDropItGenericFailure {
            get {
                return ResourceManager.GetString("ReportUtDropItGenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Ok
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusOk {
            get {
                return ResourceManager.GetString("StatusOk", resourceCulture);
            }
        }
    }
}
